### ISSUE TITLE
[Perf] It would be more appropriate to change the team in the configuration item to team_id

### ISSUE THREAD

**Issue by tyler0111** [selefra/selefra-provider-vercel#4]
It would be more appropriate to change the team in the configuration item to team_id

When it is written as team, people will mistakenly think that it should be filled with team name, but in fact it should be filled with team id, so it would be more appropriate to call it team_id. @WarrenLau1 

<img width="479" alt="image" src="https://user-images.githubusercontent.com/124039940/223664873-82cff227-aa59-4e6d-9295-f9f23e0090a0.png">

**Comment by WarrenLau1** [comment]
It has been fixed
